version: '3'
services:
        myapp:
                image: nginx
        myproxy:
                container_name: myproxy
                image: myproxy
                ports: 
                        - 80:80

